project:
  type: website
  output-dir: _site
  render: 
    - index.qmd

website:
  title: "水産海洋データ解析演習"
  site-url: https://gnishihara.github.io/rinkai2022/
  repo-url: https://github.com/gnishihara/rinkai2022/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
  
