project:
  type: website
  output-dir: _site
  render: 
    - index.qmd
    - part01.qmd
    - part02.qmd
    - part03.qmd
    - part04.qmd
    - part05.qmd
    - summary-statistics.qmd
    - ttest.qmd
    - anova.qmd
    - anova2.qmd
    - glm.qmd
    - nonlinear.qmd
    - maps.qmd
    - windfetch.qmd

website:
  title: "研究室と講義の R コード"
  site-url: https://gnishihara.github.io/rinkai2022/
  repo-url: https://github.com/gnishihara/rinkai2022/
  sidebar:
    style: "docked"
    search: true
    contents: 
      - section: "Main"
        contents:
        - index.qmd
      - section: "基本編"
        contents: 
        - part01.qmd
        - part02.qmd
        - part03.qmd
        - part04.qmd
      - section: "作図"
        contents:
        - part05.qmd
      - section: "基礎統計学"
        contents:
        - summary-statistics.qmd
        - ttest.qmd
        - anova.qmd
        - anova2.qmd
        - glm.qmd
        - nonlinear.qmd
      - section: "その他"
        contents:
        - maps.qmd
        - windfetch.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    html-math-method: katex

execute:
  freeze: auto
  
